stages:
  - publish
  - deploy-frontend


publish-frontend:
  image: docker:latest
  stage: publish
  variables:
   DOCKER_TLS_CERTDIR: ""
   DOCKER_HOST: "tcp://docker:2375"
  services:
   - docker:dind
  script:
   - cd frontend/
   - pwd
   - ls
   - docker --version
   - unset DOCKER_HOST
   - sudo chmod 666 /var/run/docker.sock
   - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
   - docker build -t b00977003/serverless-expense-tracker . -f Dockerfile
   - docker push b00977003/serverless-expense-tracker
  only:
    - main

