stages:
  - publish
  - deploy-frontend

publish-frontend:
  image: docker:latest
  stage: publish
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - cd frontend/
    - pwd
    - ls
    - docker --version
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    - docker build -t b00977003/serverless-expense-tracker . -f Dockerfile
    - docker push b00977003/serverless-expense-tracker
  only:
    - main
