stages:
  - publish
  - deploy-frontend

publish-frontend:
  image: docker:20.10.7
  stage: publish
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:20.10.7-dind
      alias: docker
  script:
    - cd frontend/
    - pwd
    - ls
    - docker --version
    - apk add --no-cache curl
    - echo "Checking Docker daemon status..."
    - curl http://docker:2375/_ping
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    - docker build -t b00977003/serverless-expense-tracker . -f Dockerfile
    - docker push b00977003/serverless-expense-tracker
  only:
    - main
