stages:
  - publish
  - deploy-frontend

publish-frontend:
  when: manual
  stage: publish
  image: docker:latest
  tags:
    - dalfcs_gitlab_docker_ci
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - "docker:dind"
  script:
    - cd frontend/
    - pwd
    - ls
    - docker --version
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    - docker build -t b00977003/serverless-expense-tracker . -f Dockerfile
    - docker push b00977003/serverless-expense-tracker
  only:
    - test

deploy-frontend:
  stage: deploy-frontend
  image: alpine:latest
  before_script:
    - apk update && apk add openssh
  script:
    - echo $SSH_PRIVATE_KEY | tr -d '\r' > /tmp/id_rsa
    - cat /tmp/id_rsa
    - chmod 600 /tmp/id_rsa
    # - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    # - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ec2-user@$EC2_HOST << 'EOF'
    #   docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    #   docker pull b00977003/serverless-expense-tracker
    #   docker stop expense-tracker || true
    #   docker rm expense-tracker || true
    #   docker run -d -p 80:80 --name expense-tracker b00977003/serverless-expense-tracker
    #   EOF
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "docker pull b00977003/serverless-expense-tracker"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "docker stop expense-tracker || true"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "docker rm expense-tracker || true"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "docker run -d -p 80:80 --name expense-tracker b00977003/serverless-expense-tracker"
  only:
    - main